[package]
name = "eddo"
version = "0.1.0"
edition = "2018"
description = "Ed25519 signatures (don't use)"
license = "MIT"

[lib]
name = "eddo"
path = "src/lib.rs"

[[bin]]
name = "eddo"
path = "src/bin.rs"

[dependencies]

